name: Quality Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Run Build
      run: make build

  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Run Test Binary Functions
      env:
        TERM: xterm
      run: make run-test bin=compute_binary_tests

    - name: Run Test Decimal Functions
      env:
        TERM: xterm
      run: make run-test bin=compute_decimal_tests

    - name: Run Test Helper Functions
      env:
        TERM: xterm
      run: make run-test bin="helper_tests"
